#!/bin/bash
#
if ! [ $(id -u) -ne 0 ]; then
 echo "Seda tuleb teha root kasutajana"
 exit 1
else
echo "Sisesta faili nimi"
read fail
input="./$fail"
while IFS= read line
do
	kasutaja=$( echo "$line" | cut -d\: -f1 )
	parool=$( echo "$line" | cut -d\: -f2  )
echo `useradd $kasutaja `
echo $kasutaja:$parool | chpasswd
echo 'kasutajate lisamine'
#echo "$parool" | chpasswd
#echo -e "$password"
done < "$fail"
fi
